❌ RED 1561739546 - OUTPUT
> greeting@1.0.0 test /home/sapagat/sandbox/bowling
> jasmine --reporter=jasmine-console-reporter

Executing 3 defined specs...
Running in random order... (seed: 68715)

Test Suites & Specs:

1. Bowling
   ✖ scores one point if only one pin knocked in the game (1 failure) (1ms)
   ✔ scores no points when no pins knocked in the game (1ms)
   ✖ sums the pins knocked in the first roll of each frame (1 failure) (<1ms)

>> Done!

Failed Specs:

1. Bowling : scores one point if only one pin knocked in the game
   ReferenceError: add is not defined
       at <Jasmine>
       at sumPinsKnocked /home/sapagat/sandbox/bowling/spec/bowlingSpec.js:46:22
       at computeScore /home/sapagat/sandbox/bowling/spec/bowlingSpec.js:34:10
       at UserContext.it /home/sapagat/sandbox/bowling/spec/bowlingSpec.js:13:19
       at <Jasmine>
       at runCallback timers.js:705:18

2. Bowling : sums the pins knocked in the first roll of each frame
   ReferenceError: add is not defined
       at <Jasmine>
       at sumPinsKnocked /home/sapagat/sandbox/bowling/spec/bowlingSpec.js:46:22
       at computeScore /home/sapagat/sandbox/bowling/spec/bowlingSpec.js:34:10
       at UserContext.it /home/sapagat/sandbox/bowling/spec/bowlingSpec.js:21:19
       at <Jasmine>
       at runCallback timers.js:705:18

Summary:

❌  Failed
Suites:  1 of 1
Specs:   3 of 3
Expects: 3 (2 failures)
Finished in 0.008 seconds