❌ RED 1561744089 - OUTPUT
> greeting@1.0.0 test /home/sapagat/sandbox/bowling
> jasmine --reporter=jasmine-console-reporter

Executing 5 defined specs...
Running in random order... (seed: 08361)

Test Suites & Specs:

1. Bowling
   ✖ computes the score of a game with a spare in the first frame (1 failure) (1ms)
   ! computes the score of a game with a single spare
   ✔ scores one point if only one pin knocked in the game (1ms)
   ✔ sums the pins knocked in each roll of the game (<1ms)
   ✔ scores no points when no pins knocked in the game (<1ms)

>> Done!

Failed Specs:

1. Bowling : computes the score of a game with a spare in the first frame
   TypeError: secondRolls.pinsKnocked is not a function
       at <Jasmine>
       at computeScore /home/sapagat/sandbox/bowling/spec/bowlingSpec.js:54:42
       at UserContext.it /home/sapagat/sandbox/bowling/spec/bowlingSpec.js:29:19
       at <Jasmine>
       at runCallback timers.js:705:18
       at tryOnImmediate timers.js:676:5

Pending Specs:

1. Bowling : computes the score of a game with a single spare
   Reason: Temporarily disabled with xit

Summary:

❌  Failed
Suites:  1 of 1
Specs:   4 of 5 (1 pending)
Expects: 4 (1 failure)
Finished in 0.01 seconds