❌ RED 1561735874 - OUTPUT
> greeting@1.0.0 test /home/sapagat/sandbox/bowling
> jasmine --reporter=jasmine-console-reporter

Executing 1 defined specs...
Running in random order... (seed: 63063)

Test Suites & Specs:

1. Bowling
   ✖ scores no points when no pins knocked in the game (1 failure) (1ms)

>> Done!

Failed Specs:

1. Bowling : scores no points when no pins knocked in the game
   ReferenceError: computeScore is not defined
       at <Jasmine>
       at UserContext.it /home/sapagat/sandbox/bowling/spec/bowlingSpec.js:5:19
       at <Jasmine>
       at runCallback timers.js:705:18
       at tryOnImmediate timers.js:676:5
       at processImmediate timers.js:658:5

Summary:

❌  Failed
Suites:  1 of 1
Specs:   1 of 1
Expects: 1 (1 failure)
Finished in 0.006 seconds